### ISSUE TITLE
Project manifests -- draft

### ISSUE THREAD

**Issue by jeremydouglass** [whatevery1says/manifest#2]
The projects file is named `project-manifests-draft.md`

Is our goal to have this out of draft before the end of the project? Should we just assign it an early release -- 0.1, 0.2 -- and release what we have?

**Comment by scottkleinman** [comment]
We've been using 2.0, but that was somewhat arbitrary and not based on semantic versioning. The schema needs a couple of tweaks, and then I think we should do a reset and assign an early release.

**Correction:** I didn't read this issue closely enough and thought it was about the manifest schema as a whole. I think the project manifests draft should be integrated into the main schema.

**Comment by scottkleinman** [comment]
We have been using the cut-down version of what is proposed in the draft, and it's not clear if the rest of the proposal will go forward. I have moved `project-manifest-draft.md` to a new `archived` folder.
